#!/bin/bash
#
# This file is part of danilo-base
#
# danilo-base is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.

# Paths
SKEL=/etc/skel

# Configuration files
BASH=.bashrc

# List of files to divert
divertList="
 $SKEL/$BASH
 "

# Divert files
for file in $divertList; do
    if test -f $file; then
        dpkg-divert --package danilo-base --add --rename \
                    --divert $file{.real,}
    fi
done
